= Universalwissen

. Universalwissen soll für alle frei zugänglich sein.
. Sämtliche Erkenntnisse und Errungenschaften von Menschen sollen der gesamten Gesellschaft zur Verfügung stehen.
. Universalwissen darf nicht privatisiert und exklusiv gehandelt werden.

== Kommentar

Das Wort `Wissen` ist zu allgemein und umfasst auch private Aspekte wie z.B. Informationen über ein Individum, 
welche aufgrund des Persönlichkeitsrechts zu schützen sind.
Universalwissen soll alles Wissen bezeichnen, was allgemeingültig ist (alle Erkenntisse der Naturwissenschaften, Erfindungen, usw.)
Im vorherschenden Wirtschaftssystem wird Universalwissen von privaten Unternehmen geheimgehalten, um sich Wettbewerbsvorteile zu sichern.
Mit Patenten werden Konkurenten vom Markt ausgeschlossen. Das alles geht zu lasten der Gesellschaft und des Fortschritts.
Wenn der Mensch im Mittelpunkt steht und nicht mehr das Geld, können wir das Universalwissen befreien und als Gesellschaft maximal vom Fortschritt profitieren.
Dann stehen auch die Erfinder im Zentrum einer Entdeckung und erhalten die gebührende Aufmerksamkeit und Anerkennung und nicht mehr die Unternehmen.
